apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::171284663551:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-gFmU9tPvpFOy
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::171284663551:role/UdacityFlaskDeployCBKubectlRole
      username: build        
kind: ConfigMap
metadata:
  creationTimestamp: "2025-05-25T06:53:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1190"
  uid: 37586e92-ff8c-480f-8435-b2a67e42f1d6
